FROM golang:latest

LABEL maintainer="akshit <akshit19991024@gmail.com>"

RUN mkdir -p /app

WORKDIR /app

COPY go.sum .
COPY go.mod .

RUN go mod download

COPY . .

COPY backend/server.go .

RUN go build  ./backend/server.go

EXPOSE $PORT

CMD ["./server"]
