FROM golang:latest

LABEL maintainer="akshit <akshit19991024@gmail.com>"

RUN mkdir -p /app/src

WORKDIR /app/src

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

COPY backend/server.go .

RUN go build -o server .

EXPOSE 3000

CMD ["./server"]
