
FROM golang:latest

LABEL maintainer="akshit <akshit19991024@gmail.com>"

RUN mkdir -p /app

WORKDIR /app

COPY go.mod .

RUN go mod download

COPY . .

COPY backend/server.go .

RUN go build -o server .

EXPOSE $PORT

COPY frontend/server1.go .

RUN go build -o server1 .

EXPOSE $PORT

CMD ["./server"]

CMD ["./server1"]

ENTRYPOINT ["app", "-f=7", "-s=9"]
